{% set name = "iniconfig" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 150a59361017218f4621a68ea9984772675a7f6e074ff7d02e115152f1804dc6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python

test:
  imports:
    - iniconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/RonnyPfannschmidt/iniconfig
  summary: 'iniconfig: brain-dead simple config-ini parsing'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
